acoustic_features:
  number_of_mels: 128
  number_of_frames_to_concatenate: 5

  frame_size_seconds: 0.064
  frame_size_samples: 1024

  hop_size_seconds: 0.032
  hop_size_samples: 512

training_parameters:
  batch_size: 256
  epochs: 10
  learning_rate: 0.001
  shuffle: True