acoustic_features:
  number_of_mels: 128
  number_of_frames_to_concatenate: 5

  frame_size_seconds: 0.064
  frame_size_samples: 1024

  hop_size_seconds: 0.032
  hop_size_samples: 512

dataset_parameters:
  train_data_inclusion_string: 'train'
  test_data_inclusion_string: 'test'
  train_pct: 1
  test_pct: 1

training_parameters:
  batch_size: 256
  epochs: 100
  learning_rate: 0.001
  shuffle: True